### ISSUE TITLE
You don't seem to have a generator with the name angularfire-fab installed

### ISSUE THREAD

**Issue by ralyodio** [FabVillegas/generator-angularfire-fab#1]
$ yo angularfire-fab
Error angularfire-fab

You don't seem to have a generator with the name angularfire-fab installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 16 registered generators run yo with the `--help` option.

**Comment by FabVillegas** [comment]
Sorry for being late, I'm working on the problem, seems to be related to some modules and dependencies with deprecated versions.

I'll update the files.

**Comment by FabVillegas** [comment]
It should work now. Uninstall the module first.
